######################################################################
# Automatically generated by qmake (2.01a) wt. lut 23 16:01:33 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
